from typing import Any

def enumerate(vid: int, pid: int) -> list[dict[str, Any]]: ...

class device:
    def __init__(self) -> None: ...
    def open(self, vid: int, pid: int) -> None: ...
    def open_path(self, path: str | bytes) -> None: ...
    def write(self, data: bytes | bytearray) -> int: ...
    def read(self, size: int, timeout_ms: int | None = ...) -> bytes: ...
    def close(self) -> None: ...
